Remove unused ignore in logutils
```
src/matrix_content_scanner/logutils.py:35: error: Unused "type: ignore" comment  [unused-ignore]
```

The paragraph starting

> This functionality can be used to inject your own values

in https://docs.python.org/3/library/logging.html#logging.LogRecord
seems to suggest our use is legitimate. Mypy things `record.request_id`
is Any, according to reveal_type.

Typeshed was changed to account for this in https://github.com/python/typeshed/issues/7833